### ISSUE TITLE
Enable targeting supervisors outside of the targeted applications

### ISSUE THREAD

**Issue by juhlig** [ankhers/havoc#14]
https://github.com/ankhers/havoc/blob/24eb58b9a3dcda1ee5df61cfbb39f3d7190aeea5/src/havoc.erl#L253-L254

Shouldn't `app_killable` and `supervisor_killable` be `orelse`d? It makes no sense to be able to specify both: If you specify a supervisor _and_ an app, the supervisor _must_ be part of that app, otherwise nothing will ever be found for killing. So it is really pointless to specify an app if you also specify a supervisor.

By substituting `andalso` for `orelse`, it would be possible to target apps and supervisors _outside_ of those specified apps. And this is just what we would like to be able to do: target the entire `ranch` application, _plus_ a certain supervisor under the `ssl` application.

**Comment by ankhers** [comment]
I think you are right here. I will go through the current options and see which ones should be `orelse`d together.

**Comment by ankhers** [comment]
resolved in 38ce53f05d21b5f2d1364df1bb3068422660748c

**Comment by juhlig** [comment]
Turns out it is not as simple as just `orelse`... Now, if you omit `supervisors`, it means "kill processes from that app _or any supervisor_", which boils down to `kill processes from any supervisor" =^^=

**Comment by ankhers** [comment]
Should be actually fixed now in 69d4b47ddfc8bac0687526add0a1973fcfc27206.
